name: Publish to Github

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  github_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"
          node-version: 16

      - name: Publish to github packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}